version: "3.3"
services:
  freefit-api:
    image: freefit-api
    build: .
    ports:
      - 3000:3000
    depends_on:
      - freefit-db
    environment:
      - POSTGRES_HOST=freefit-db
  freefit-db:
    image: postgres:10.4
    container_name: freefit-db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./docker/scripts:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=freefit,freefit_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:5.0.3
    container_name: freefit-redis
    ports:
      - 6379:6379
